#!/bin/sh
#
# redis this script starts and stops the mongodb daemon
#
# chkconfig: - 85 15
# description: redis is a non-relational database storage system. 
# processname: redis

NAME=redis

case "$1" in
	start)
		echo -n "Starting Redis... "
		redis-server /etc/redis.conf
		;;
	stop)
		echo -n "Stopping Redis"
		pkill redis-server
		;;
	*)
		N=/etc/init.d/$NAME
		echo "Usage: $N {start|stop}" >&2
		exit 1
		;;
esac

exit 0
